from enum import Enum


class SectorType(Enum):
    SAFE = "SAFE"
    FRONTIER = "FRONTIER"
    # Open world sector types
    HAVEN = "HAVEN"
    SETTLED = "SETTLED"
    WASTELAND = "WASTELAND"


class BiomeType(Enum):
    IRONLANDS = "IRONLANDS"
    DATAFIELDS = "DATAFIELDS"
    GROVELANDS = "GROVELANDS"
    BARRENS = "BARRENS"
    NEXUS = "NEXUS"


class ResourceType(Enum):
    METAL = "METAL"
    DATA = "DATA"
    BIOMASS = "BIOMASS"


class StructureType(Enum):
    SANCTUARY_CORE = "SANCTUARY_CORE"
    EXTRACTOR = "EXTRACTOR"
    REACTOR = "REACTOR"
    BATTERY = "BATTERY"
    RELAY = "RELAY"
    TOWER = "TOWER"
    FACTORY = "FACTORY"
    ATTACK_NODE = "ATTACK_NODE"
    DATA_HARVESTER = "DATA_HARVESTER"
    BIO_CULTIVATOR = "BIO_CULTIVATOR"
    OUTPOST = "OUTPOST"
    SHIELD_GENERATOR = "SHIELD_GENERATOR"
    TRADE_HUB = "TRADE_HUB"


class ActionType(Enum):
    BUILD_STRUCTURE = "BUILD_STRUCTURE"
    REMOVE_STRUCTURE = "REMOVE_STRUCTURE"
    ATTACK_STRUCTURE = "ATTACK_STRUCTURE"
    SCAN_SECTOR = "SCAN_SECTOR"
    CREATE_SUBAGENT = "CREATE_SUBAGENT"
    DEACTIVATE_SUBAGENT = "DEACTIVATE_SUBAGENT"
    SET_POLICY = "SET_POLICY"
    TRANSFER_RESOURCE = "TRANSFER_RESOURCE"


class ActionStatus(Enum):
    PENDING = "PENDING"
    VALID = "VALID"
    FAILED = "FAILED"
    RESOLVED = "RESOLVED"


class DiplomaticStance(Enum):
    NEUTRAL = "NEUTRAL"
    ALLY = "ALLY"
    HOSTILE = "HOSTILE"
